language: go

go:
  - 1.9
  - tip

os:
  - linux

before_install:
  - go get -d -t ./...
  - go test -i ./...

script:
  - cd $TRAVIS_BUILD_DIR
  - go test -race -coverprofile=coverage.txt -covermode=atomic

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
